from turtle import *
turtle = Turtle()
screen = Screen()
screen.bgcolor("black")
turtle.pensize(3)
def kare_ciz():
    turtle.goto(0,0)
    turtle.color("red")
    turtle.fillcolor ("red")
    turtle.left (45)
    turtle.begin_fill()
    for i in range (2):
        turtle. forward (100)
        turtle.left (90)
        turtle.forward (100)
        turtle.left (90)
    turtle.end_fill()
        
def ucgen_ciz():
    turtle.pensize(3)
    turtle.fillcolor ("blue")
    turtle.begin_fill()
    turtle.color("blue")
    turtle.goto(-45,45)
    turtle.right (45)
    turtle.forward (90)
    turtle.right (135)
    turtle.forward (65)
    turtle.end_fill()
def mesale_ciz():
    turtle.pensize(3)
    turtle.fillcolor("white")
    turtle.color("blue")
    turtle.goto(-45,45)
    turtle.begin_fill()
    turtle.color("white")
    turtle.right(110)
    turtle.forward(40)
    turtle.right(160)
    turtle.forward(40)
    turtle.left(150)
    turtle.forward(45)
    turtle.right(160)
    turtle.forward(40)
    turtle.left(150)
    turtle.forward(50)
    turtle.right(160)
    turtle.forward(45)
    turtle.left(149)
    turtle.forward(70)
    turtle.right(160)
    turtle.forward(70)
    turtle.left(150)
    turtle.forward(40)
    turtle.right (160)
    turtle.forward(50)
    turtle.left(150)
    turtle.forward(36)
    turtle.right(160)
    turtle.forward(40)
    turtle.left(150)
    turtle.forward(30)
    turtle.right(165)
    turtle.forward(36)
    turtle.right (69)
    turtle.forward(90)
    turtle.end_fill()

kare_ciz()
ucgen_ciz()
mesale_ciz()